import type { SitecoreNode } from "../types";

// ============================================================================
// VIRTUAL SITECORE CONTENT TREE
// ============================================================================

const TREE_DATA: { sitecore: SitecoreNode } = {
  sitecore: {
    _id: "{11111111-1111-1111-1111-111111111111}",
    _template: "Root",
    _templateFullName: "System/Root",
    _version: 1,
    _fields: {},
    _children: {
      content: {
        _id: "{0DE95AE4-41AB-4D01-9EB0-67441B7C2450}",
        _template: "Node",
        _templateFullName: "System/Node",
        _version: 1,
        _fields: {},
        _children: {
          Home: {
            _id: "{110D559F-DEA5-42EA-9C1C-8A5DF7E70EF9}",
            _template: "Sample Item",
            _templateFullName: "Sample/Sample Item",
            _version: 2,
            _fields: {
              Title: "Welcome to Sitecore",
              Text: "<p>This is the home page content.</p>",
              NavigationTitle: "Home",
              MetaDescription: "Welcome to our Sitecore-powered website.",
              MetaKeywords: "sitecore, cms, content management",
              __Updated: "20250315T103000Z",
              __Created: "20240601T080000Z",
              "__Updated by": "sitecore\\admin",
            },
            _children: {
              About: {
                _id: "{A2B3C4D5-E6F7-8901-2345-678901234567}",
                _template: "Sample Item",
                _templateFullName: "Sample/Sample Item",
                _version: 1,
                _fields: {
                  Title: "About Us",
                  Text: "<p>Learn more about our company.</p>",
                  NavigationTitle: "About",
                  ShowInNavigation: "1",
                  __Updated: "20250220T140000Z",
                  __Created: "20240710T090000Z",
                  "__Updated by": "sitecore\\author1",
                },
                _children: {
                  Contributors: {
                    _id: "{B1111111-1111-1111-1111-111111111111}",
                    _template: "Sample Item",
                    _templateFullName: "Sample/Sample Item",
                    _version: 1,
                    _fields: {
                      Title: "Our Contributors",
                      Text: "<p>Meet the contributors behind the project.</p>",
                      __Updated: "20250110T110000Z",
                      __Created: "20240815T100000Z",
                      "__Updated by": "sitecore\\author1",
                    },
                    _children: {
                      "Michael West": {
                        _id: "{B1A00001-0001-0001-0001-000000000001}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Michael West",
                          GitHubUser: "michaellwest",
                          IsActive: "1",
                          SortOrder: "100",
                          Bio: "Co-creator of Sitecore PowerShell Extensions. Microsoft MVP and Sitecore MVP.",
                          Country: "United States",
                          Location: "Dallas, TX",
                          Company: "",
                          MvpYears:
                            "2015|2016|2017|2018|2019|2020|2021|2022|2023|2024|2025|2026",
                          MvpCategory: "Technology",
                          FirstMvpYear: "2015",
                          LinkedIn: "https://www.linkedin.com/in/michaellwest",
                          Twitter: "https://twitter.com/MichaelWest101",
                          Blog: "https://westtech.dev",
                          GravatarUrl: "https://github.com/michaellwest.png",
                          Website: "https://github.com/michaellwest",
                          __Updated: "20250301T090000Z",
                          __Created: "20240901T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Adam Najmanowicz": {
                        _id: "{B1A00002-0002-0002-0002-000000000002}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Adam Najmanowicz",
                          GitHubUser: "AdamNaj",
                          IsActive: "1",
                          SortOrder: "200",
                          Bio: "Co-creator of SPE. Sitecore MVP specializing in automation and tooling.",
                          Country: "Poland",
                          Location: "",
                          Company: "Cognifide",
                          MvpYears: "2011|2012|2013|2014|2015|2016|2017|2026",
                          MvpCategory: "Technology",
                          FirstMvpYear: "2011",
                          LinkedIn: "https://www.linkedin.com/in/najmanowicz",
                          Twitter: "https://twitter.com/adamnaj",
                          Blog: "https://blog.najmanowicz.com",
                          GravatarUrl: "https://github.com/AdamNaj.png",
                          Website: "https://github.com/AdamNaj",
                          __Updated: "20250218T150000Z",
                          __Created: "20240901T083000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Alex Washtell": {
                        _id: "{B1A00003-0003-0003-0003-000000000003}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Alex Washtell",
                          GitHubUser: "AlexKasaku",
                          IsActive: "1",
                          SortOrder: "300",
                          Bio: "Sitecore MVP and solutions architect focused on composable DXP.",
                          Country: "United Kingdom",
                          Location: "London",
                          Company: "Kasaku",
                          MvpYears:
                            "2017|2018|2019|2020|2021|2022|2023|2024|2025|2026",
                          MvpCategory: "Technology|Ambassador",
                          FirstMvpYear: "2017",
                          LinkedIn: "https://www.linkedin.com/in/awashtell",
                          Twitter: "https://twitter.com/kasaku_dev",
                          Blog: "https://www.kasaku.co.uk",
                          GravatarUrl: "https://github.com/AlexKasaku.png",
                          Website: "https://github.com/AlexKasaku",
                          __Updated: "20250205T110000Z",
                          __Created: "20240915T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Alan Płócieniak": {
                        _id: "{B1A00004-0004-0004-0004-000000000004}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Alan Płócieniak",
                          GitHubUser: "alan-null",
                          IsActive: "1",
                          SortOrder: "400",
                          Bio: "Community contributor and Sitecore developer.",
                          Country: "Poland",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/alan-null.png",
                          Website: "https://github.com/alan-null",
                          __Updated: "20250115T100000Z",
                          __Created: "20241010T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Rodrigo Peplau": {
                        _id: "{B1A00005-0005-0005-0005-000000000005}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Rodrigo Peplau",
                          GitHubUser: "altudopeplau",
                          IsActive: "1",
                          SortOrder: "500",
                          Bio: "Community contributor specializing in Sitecore development.",
                          Country: "Brazil",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/altudopeplau.png",
                          Website: "https://github.com/altudopeplau",
                          __Updated: "20250110T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Dan Solovay": {
                        _id: "{B1A00006-0006-0006-0006-000000000006}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Dan Solovay",
                          GitHubUser: "dsolovay",
                          IsActive: "1",
                          SortOrder: "600",
                          Bio: "Sitecore MVP and senior developer focused on content management solutions.",
                          Country: "United States",
                          Location: "Boston, MA",
                          Company: "Velir",
                          MvpYears:
                            "2013|2014|2015|2016|2017|2018|2019|2020|2021|2022|2023|2024|2025|2026",
                          MvpCategory: "Technology",
                          FirstMvpYear: "2013",
                          LinkedIn: "https://www.linkedin.com/in/dansolovay",
                          Twitter: "https://twitter.com/dansolovay",
                          Blog: "https://www.dansolovay.com",
                          GravatarUrl: "https://github.com/dsolovay.png",
                          Website: "https://github.com/dsolovay",
                          __Updated: "20250108T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Mike Reynolds": {
                        _id: "{B1A00007-0007-0007-0007-000000000007}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Mike Reynolds",
                          GitHubUser: "scjunkie",
                          IsActive: "1",
                          SortOrder: "700",
                          Bio: "Sitecore MVP and veteran developer with deep CMS expertise.",
                          Country: "United States",
                          Location: "",
                          Company: "",
                          MvpYears:
                            "2014|2015|2016|2017|2018|2019|2020|2021|2022|2023",
                          MvpCategory: "Technology|Ambassador",
                          FirstMvpYear: "2014",
                          LinkedIn:
                            "https://www.linkedin.com/in/michaelianreynolds",
                          Twitter: "https://twitter.com/mike_i_reynolds",
                          Blog: "https://sitecorejunkie.com",
                          GravatarUrl: "https://github.com/scjunkie.png",
                          Website: "https://github.com/scjunkie",
                          __Updated: "20250105T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Ro Se": {
                        _id: "{B1A00008-0008-0008-0008-000000000008}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Ro Se",
                          GitHubUser: "RobsonAutomator",
                          IsActive: "1",
                          SortOrder: "800",
                          Bio: "Community contributor focused on Sitecore automation.",
                          Country: "",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/RobsonAutomator.png",
                          Website: "https://github.com/RobsonAutomator",
                          __Updated: "20250103T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Søren Kruse": {
                        _id: "{B1A00009-0009-0009-0009-000000000009}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Søren Kruse",
                          GitHubUser: "Krusen",
                          IsActive: "1",
                          SortOrder: "900",
                          Bio: "Community contributor and Sitecore developer.",
                          Country: "Denmark",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/Krusen.png",
                          Website: "https://github.com/Krusen",
                          __Updated: "20250101T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      ptaront: {
                        _id: "{B1A00010-0010-0010-0010-000000000010}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "ptaront",
                          GitHubUser: "ptaront",
                          IsActive: "1",
                          SortOrder: "1000",
                          Bio: "Community contributor to SPE.",
                          Country: "",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/ptaront.png",
                          Website: "https://github.com/ptaront",
                          __Updated: "20241215T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Dawid Rutkowski": {
                        _id: "{B1A00011-0011-0011-0011-000000000011}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Dawid Rutkowski",
                          GitHubUser: "sc-dawidrutkowski",
                          IsActive: "1",
                          SortOrder: "1100",
                          Bio: "Community contributor and Sitecore developer.",
                          Country: "Poland",
                          Location: "",
                          Company: "Sitecore",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl:
                            "https://github.com/sc-dawidrutkowski.png",
                          Website: "https://github.com/sc-dawidrutkowski",
                          __Updated: "20241210T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      simoncroak: {
                        _id: "{B1A00012-0012-0012-0012-000000000012}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "simoncroak",
                          GitHubUser: "simoncroak",
                          IsActive: "1",
                          SortOrder: "1200",
                          Bio: "Community contributor to SPE.",
                          Country: "",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/simoncroak.png",
                          Website: "https://github.com/simoncroak",
                          __Updated: "20241205T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Marcin Zabłocki": {
                        _id: "{B1A00013-0013-0013-0013-000000000013}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Marcin Zabłocki",
                          GitHubUser: "marrrcin",
                          IsActive: "1",
                          SortOrder: "1300",
                          Bio: "Community contributor and Sitecore developer.",
                          Country: "Poland",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/marrrcin.png",
                          Website: "https://github.com/marrrcin",
                          __Updated: "20241201T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Aaron Bickle": {
                        _id: "{B1A00014-0014-0014-0014-000000000014}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Aaron Bickle",
                          GitHubUser: "bic742",
                          IsActive: "1",
                          SortOrder: "1400",
                          Bio: "Sitecore MVP and community contributor to SPE.",
                          Country: "United States",
                          Location: "",
                          Company: "",
                          MvpYears: "2020|2021|2022",
                          MvpCategory: "Technology",
                          FirstMvpYear: "2020",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/bic742.png",
                          Website: "https://github.com/bic742",
                          __Updated: "20241125T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Andy Cohen": {
                        _id: "{B1A00015-0015-0015-0015-000000000015}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Andy Cohen",
                          GitHubUser: "iamandycohen",
                          IsActive: "1",
                          SortOrder: "1500",
                          Bio: "Community contributor and Sitecore developer.",
                          Country: "United States",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/iamandycohen.png",
                          Website: "https://github.com/iamandycohen",
                          __Updated: "20241120T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Anton Kuryan": {
                        _id: "{B1A00016-0016-0016-0016-000000000016}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Anton Kuryan",
                          GitHubUser: "eptw4by",
                          IsActive: "1",
                          SortOrder: "1600",
                          Bio: "Community contributor to SPE.",
                          Country: "",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/eptw4by.png",
                          Website: "https://github.com/eptw4by",
                          __Updated: "20241115T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Benjamin Vangansewinkel": {
                        _id: "{B1A00017-0017-0017-0017-000000000017}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Benjamin Vangansewinkel",
                          GitHubUser: "VGBenjamin",
                          IsActive: "1",
                          SortOrder: "1700",
                          Bio: "Sitecore MVP and community advocate for SPE adoption.",
                          Country: "United States",
                          Location: "",
                          Company: "",
                          MvpYears: "2013|2014|2015|2016|2017|2018",
                          MvpCategory: "Technology",
                          FirstMvpYear: "2013",
                          LinkedIn:
                            "https://www.linkedin.com/in/benjamin-vangansewinkel",
                          Twitter: "",
                          Blog: "https://sitecoreblog.blogspot.com",
                          GravatarUrl: "https://github.com/VGBenjamin.png",
                          Website: "https://github.com/VGBenjamin",
                          __Updated: "20241110T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Corey Smith": {
                        _id: "{B1A00018-0018-0018-0018-000000000018}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Corey Smith",
                          GitHubUser: "coreyasmith",
                          IsActive: "1",
                          SortOrder: "1800",
                          Bio: "Sitecore MVP and solutions architect.",
                          Country: "United States",
                          Location: "",
                          Company: "Corey Smith Consulting",
                          MvpYears:
                            "2017|2018|2019|2020|2021|2022|2023|2024|2025|2026",
                          MvpCategory: "Technology",
                          FirstMvpYear: "2017",
                          LinkedIn: "https://www.linkedin.com/in/smithdev",
                          Twitter: "https://twitter.com/sitecorey",
                          Blog: "https://www.coreysmith.co",
                          GravatarUrl: "https://github.com/coreyasmith.png",
                          Website: "https://github.com/coreyasmith",
                          __Updated: "20241105T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Harsh Baid": {
                        _id: "{B1A00019-0019-0019-0019-000000000019}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Harsh Baid",
                          GitHubUser: "harshbaid",
                          IsActive: "1",
                          SortOrder: "1900",
                          Bio: "Community contributor and Sitecore developer.",
                          Country: "India",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/harshbaid.png",
                          Website: "https://github.com/harshbaid",
                          __Updated: "20241101T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Jason St-Cyr": {
                        _id: "{B1A00020-0020-0020-0020-000000000020}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Jason St-Cyr",
                          GitHubUser: "jst-cyr",
                          IsActive: "1",
                          SortOrder: "2000",
                          Bio: "Developer advocate at Sitecore and community champion.",
                          Country: "Canada",
                          Location: "Ottawa",
                          Company: "Sitecore",
                          MvpYears: "2014|2015|2016|2017|2025",
                          MvpCategory: "Technology|Strategy",
                          FirstMvpYear: "2014",
                          LinkedIn: "https://www.linkedin.com/in/jasonstcyr",
                          Twitter: "https://twitter.com/stcyrthoughts",
                          Blog: "https://jasonstcyr.com",
                          GravatarUrl: "https://github.com/jst-cyr.png",
                          Website: "https://github.com/jst-cyr",
                          __Updated: "20241025T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Mark Gibbons": {
                        _id: "{B1A00021-0021-0021-0021-000000000021}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Mark Gibbons",
                          GitHubUser: "markgibbons25",
                          IsActive: "1",
                          SortOrder: "2100",
                          Bio: "Community contributor and Sitecore developer.",
                          Country: "United Kingdom",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/markgibbons25.png",
                          Website: "https://github.com/markgibbons25",
                          __Updated: "20241020T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Özkan Sayın": {
                        _id: "{B1A00022-0022-0022-0022-000000000022}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Özkan Sayın",
                          GitHubUser: "ozkansayin",
                          IsActive: "1",
                          SortOrder: "2200",
                          Bio: "Community contributor to SPE.",
                          Country: "Turkey",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/ozkansayin.png",
                          Website: "https://github.com/ozkansayin",
                          __Updated: "20241015T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Robert Senktas": {
                        _id: "{B1A00023-0023-0023-0023-000000000023}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Robert Senktas",
                          GitHubUser: "rsenk",
                          IsActive: "1",
                          SortOrder: "2300",
                          Bio: "Community contributor and Sitecore developer.",
                          Country: "Poland",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/rsenk.png",
                          Website: "https://github.com/rsenk",
                          __Updated: "20241010T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      Stanislav: {
                        _id: "{B1A00024-0024-0024-0024-000000000024}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Stanislav",
                          GitHubUser: "stanislavSV",
                          IsActive: "1",
                          SortOrder: "2400",
                          Bio: "Community contributor to SPE.",
                          Country: "",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/stanislavSV.png",
                          Website: "https://github.com/stanislavSV",
                          __Updated: "20241005T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "Szymon Kuźniak": {
                        _id: "{B1A00025-0025-0025-0025-000000000025}",
                        _template: "Contributor",
                        _templateFullName: "Project/Contributor",
                        _version: 1,
                        _fields: {
                          Title: "Szymon Kuźniak",
                          GitHubUser: "cogskuzniak",
                          IsActive: "1",
                          SortOrder: "2500",
                          Bio: "Community contributor and Sitecore developer.",
                          Country: "Poland",
                          Location: "",
                          Company: "",
                          MvpYears: "",
                          MvpCategory: "",
                          FirstMvpYear: "",
                          LinkedIn: "",
                          Twitter: "",
                          Blog: "",
                          GravatarUrl: "https://github.com/cogskuzniak.png",
                          Website: "https://github.com/cogskuzniak",
                          __Updated: "20241001T090000Z",
                          __Created: "20241001T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                    },
                  },
                  History: {
                    _id: "{B2222222-2222-2222-2222-222222222222}",
                    _template: "Sample Item",
                    _templateFullName: "Sample/Sample Item",
                    _version: 1,
                    _fields: {
                      Title: "Our History",
                      Text: "<p>Founded in 2003.</p>",
                      __Updated: "20250105T090000Z",
                      __Created: "20240815T103000Z",
                      "__Updated by": "sitecore\\admin",
                    },
                    _children: {},
                  },
                  Careers: {
                    _id: "{A2C00001-0001-0001-0001-000000000001}",
                    _template: "Landing Page",
                    _templateFullName: "Project/Landing Page",
                    _version: 1,
                    _fields: {
                      Title: "Join Our Contributors",
                      Text: "<p>We are always looking for talented individuals.</p>",
                      HeroBanner: "{F1A00001-0001-0001-0001-000000000001}",
                      CallToAction: "View Open Positions",
                      ShowInNavigation: "1",
                      __Updated: "20250308T140000Z",
                      __Created: "20250101T090000Z",
                      "__Updated by": "sitecore\\author1",
                    },
                    _children: {},
                  },
                },
              },
              Products: {
                _id: "{C3D4E5F6-7890-1234-5678-901234567890}",
                _template: "Folder",
                _templateFullName: "Common/Folder",
                _version: 1,
                _fields: {
                  __Updated: "20250301T080000Z",
                  __Created: "20240615T120000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {
                  "XM Cloud": {
                    _id: "{D1111111-1111-1111-1111-111111111111}",
                    _template: "Product",
                    _templateFullName: "Project/Product",
                    _version: 1,
                    _fields: {
                      Title: "XM Cloud",
                      Text: "<p>Composable CMS for modern web experiences.</p>",
                      Price: "499.99",
                      SKU: "XMC-001",
                      Category: "CMS",
                      IsActive: "1",
                      ReleaseDate: "20240901",
                      __Updated: "20250310T160000Z",
                      __Created: "20240901T080000Z",
                      "__Updated by": "sitecore\\author2",
                    },
                    _children: {
                      Features: {
                        _id: "{D1F00001-0001-0001-0001-000000000001}",
                        _template: "Folder",
                        _templateFullName: "Common/Folder",
                        _version: 1,
                        _fields: {
                          __Updated: "20250310T160000Z",
                          __Created: "20240901T090000Z",
                          "__Updated by": "sitecore\\author2",
                        },
                        _children: {
                          "Pages Editor": {
                            _id: "{D1F00002-0002-0002-0002-000000000002}",
                            _template: "Feature",
                            _templateFullName: "Project/Feature",
                            _version: 1,
                            _fields: {
                              Title: "Pages Editor",
                              Text: "<p>Visual page editing with drag-and-drop components.</p>",
                              Priority: "High",
                              __Updated: "20250310T160000Z",
                              __Created: "20240905T100000Z",
                              "__Updated by": "sitecore\\author2",
                            },
                            _children: {},
                          },
                          Components: {
                            _id: "{D1F00003-0003-0003-0003-000000000003}",
                            _template: "Feature",
                            _templateFullName: "Project/Feature",
                            _version: 1,
                            _fields: {
                              Title: "Components",
                              Text: "<p>Reusable front-end components for headless rendering.</p>",
                              Priority: "Medium",
                              __Updated: "20250228T120000Z",
                              __Created: "20240905T103000Z",
                              "__Updated by": "sitecore\\author2",
                            },
                            _children: {},
                          },
                          Forms: {
                            _id: "{D1F00004-0004-0004-0004-000000000004}",
                            _template: "Feature",
                            _templateFullName: "Project/Feature",
                            _version: 1,
                            _fields: {
                              Title: "Forms",
                              Text: "<p>Drag-and-drop form builder with analytics.</p>",
                              Priority: "Medium",
                              __Updated: "20250310T160000Z",
                              __Created: "20240910T100000Z",
                              "__Updated by": "sitecore\\author2",
                            },
                            _children: {},
                          },
                        },
                      },
                    },
                  },
                  "Content Hub": {
                    _id: "{D2222222-2222-2222-2222-222222222222}",
                    _template: "Product",
                    _templateFullName: "Project/Product",
                    _version: 1,
                    _fields: {
                      Title: "Content Hub",
                      Text: "<p>Digital asset management and content operations.</p>",
                      Price: "1299.00",
                      SKU: "CH-001",
                      Category: "DAM",
                      IsActive: "1",
                      ReleaseDate: "20240915",
                      __Updated: "20250228T120000Z",
                      __Created: "20240915T100000Z",
                      "__Updated by": "sitecore\\author2",
                    },
                    _children: {},
                  },
                  "Sitecore Search": {
                    _id: "{D3333333-3333-3333-3333-333333333333}",
                    _template: "Product",
                    _templateFullName: "Project/Product",
                    _version: 1,
                    _fields: {
                      Title: "Sitecore Search",
                      Text: "<p>AI-powered search and discovery service.</p>",
                      Price: "199.00",
                      SKU: "SS-001",
                      Category: "Search",
                      IsActive: "1",
                      ReleaseDate: "20241001",
                      __Updated: "20250120T143000Z",
                      __Created: "20241001T090000Z",
                      "__Updated by": "sitecore\\admin",
                    },
                    _children: {},
                  },
                  "Sitecore Send": {
                    _id: "{D4444444-4444-4444-4444-444444444444}",
                    _template: "Product",
                    _templateFullName: "Project/Product",
                    _version: 1,
                    _fields: {
                      Title: "Sitecore Send",
                      Text: "<p>Email marketing and automation platform.</p>",
                      Price: "799.00",
                      SKU: "SEND-001",
                      Category: "Marketing",
                      IsActive: "0",
                      ReleaseDate: "20250301",
                      __Updated: "20250305T090000Z",
                      __Created: "20250201T080000Z",
                      "__Updated by": "sitecore\\author2",
                    },
                    _children: {},
                  },
                },
              },
              News: {
                _id: "{E4F5A6B7-C8D9-0123-4567-890123456789}",
                _template: "Folder",
                _templateFullName: "Common/Folder",
                _version: 1,
                _fields: {
                  __Updated: "20250312T090000Z",
                  __Created: "20240701T080000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {
                  "SPE 7.0 Released": {
                    _id: "{E1111111-1111-1111-1111-111111111111}",
                    _template: "Article",
                    _templateFullName: "Project/Article",
                    _version: 1,
                    _fields: {
                      Title: "SPE 7.0 Released",
                      Text: "<p>Major release with XM Cloud support and new cmdlets.</p>",
                      Summary:
                        "SPE 7.0 brings first-class XM Cloud support and over 20 new cmdlets.",
                      Author: "Michael West",
                      PublishDate: "20250105",
                      Category: "Release",
                      Tags: "spe, release, xm cloud",
                      __Updated: "20250312T090000Z",
                      __Created: "20250105T080000Z",
                      "__Updated by": "sitecore\\author1",
                    },
                    _children: {},
                  },
                  "SPE Remoting Update": {
                    _id: "{E2222222-2222-2222-2222-222222222222}",
                    _template: "Article",
                    _templateFullName: "Project/Article",
                    _version: 1,
                    _fields: {
                      Title: "SPE Remoting Update",
                      Text: "<p>Updated remoting module with improved authentication.</p>",
                      Summary:
                        "The SPE Remoting module now supports modern authentication flows.",
                      Author: "Adam Najmanowicz",
                      PublishDate: "20241120",
                      Category: "Module",
                      Tags: "spe, remoting, authentication",
                      __Updated: "20250215T110000Z",
                      __Created: "20241120T100000Z",
                      "__Updated by": "sitecore\\author2",
                    },
                    _children: {},
                  },
                  "SPE XM Cloud Support": {
                    _id: "{E3333333-3333-3333-3333-333333333333}",
                    _template: "Article",
                    _templateFullName: "Project/Article",
                    _version: 1,
                    _fields: {
                      Title: "SPE XM Cloud Support",
                      Text: "<p>Full composable DXP integration for SPE.</p>",
                      Summary:
                        "SPE now integrates natively with Sitecore's composable DXP architecture.",
                      Author: "Alex Washtell",
                      PublishDate: "20250401",
                      Category: "Integration",
                      Tags: "spe, xm cloud, composable",
                      __Updated: "20250401T090000Z",
                      __Created: "20250325T100000Z",
                      "__Updated by": "sitecore\\author1",
                    },
                    _children: {},
                  },
                  "SPE 6.4 Security Patch": {
                    _id: "{E4444444-4444-4444-4444-444444444444}",
                    _template: "Article",
                    _templateFullName: "Project/Article",
                    _version: 1,
                    _fields: {
                      Title: "SPE 6.4 Security Patch",
                      Text: "<p>Critical security update for SPE 6.4.</p>",
                      Summary:
                        "Addresses a privilege escalation vulnerability in script execution.",
                      Author: "Michael West",
                      PublishDate: "20250210",
                      Category: "Security",
                      Tags: "spe, security, patch",
                      __Updated: "20250210T140000Z",
                      __Created: "20250205T100000Z",
                      "__Updated by": "sitecore\\admin",
                    },
                    _children: {},
                  },
                },
              },
            },
          },
          Data: {
            _id: "{0DA00001-DA1A-DA1A-DA1A-DA1A00000001}",
            _template: "Folder",
            _templateFullName: "Common/Folder",
            _version: 1,
            _fields: {
              __Updated: "20250101T080000Z",
              __Created: "20240601T080000Z",
              "__Updated by": "sitecore\\admin",
            },
            _children: {
              Settings: {
                _id: "{0DA00002-DA2A-DA2A-DA2A-DA2A00000002}",
                _template: "Configuration",
                _templateFullName: "Project/Configuration",
                _version: 1,
                _fields: {
                  Title: "Global Settings",
                  SiteName: "Corporate Website",
                  DefaultLanguage: "en",
                  MaxPageSize: "50",
                  EnableSearch: "1",
                  AnalyticsEnabled: "1",
                  CacheTimeout: "3600",
                  __Updated: "20250310T100000Z",
                  __Created: "20240601T080000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {},
              },
              Lookups: {
                _id: "{0DA00003-DA3A-DA3A-DA3A-DA3A00000003}",
                _template: "Folder",
                _templateFullName: "Common/Folder",
                _version: 1,
                _fields: {
                  __Updated: "20250101T080000Z",
                  __Created: "20240601T090000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {
                  Countries: {
                    _id: "{0DA00004-DA4A-DA4A-DA4A-DA4A00000004}",
                    _template: "Folder",
                    _templateFullName: "Common/Folder",
                    _version: 1,
                    _fields: {
                      __Updated: "20240801T080000Z",
                      __Created: "20240601T090000Z",
                      "__Updated by": "sitecore\\admin",
                    },
                    _children: {
                      "United States": {
                        _id: "{0DA00005-DA5A-DA5A-DA5A-DA5A00000005}",
                        _template: "Lookup Item",
                        _templateFullName: "Common/Lookup Item",
                        _version: 1,
                        _fields: {
                          Title: "United States",
                          Value: "US",
                          SortOrder: "100",
                          __Updated: "20240801T080000Z",
                          __Created: "20240601T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      Canada: {
                        _id: "{0DA00006-DA6A-DA6A-DA6A-DA6A00000006}",
                        _template: "Lookup Item",
                        _templateFullName: "Common/Lookup Item",
                        _version: 1,
                        _fields: {
                          Title: "Canada",
                          Value: "CA",
                          SortOrder: "200",
                          __Updated: "20240801T080000Z",
                          __Created: "20240601T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "United Kingdom": {
                        _id: "{0DA00007-DA7A-DA7A-DA7A-DA7A00000007}",
                        _template: "Lookup Item",
                        _templateFullName: "Common/Lookup Item",
                        _version: 1,
                        _fields: {
                          Title: "United Kingdom",
                          Value: "UK",
                          SortOrder: "300",
                          __Updated: "20240801T080000Z",
                          __Created: "20240601T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                    },
                  },
                  Categories: {
                    _id: "{0DA00008-DA8A-DA8A-DA8A-DA8A00000008}",
                    _template: "Folder",
                    _templateFullName: "Common/Folder",
                    _version: 1,
                    _fields: {
                      __Updated: "20240801T080000Z",
                      __Created: "20240601T090000Z",
                      "__Updated by": "sitecore\\admin",
                    },
                    _children: {
                      Technology: {
                        _id: "{0DA00009-DA9A-DA9A-DA9A-DA9A00000009}",
                        _template: "Lookup Item",
                        _templateFullName: "Common/Lookup Item",
                        _version: 1,
                        _fields: {
                          Title: "Technology",
                          Value: "technology",
                          SortOrder: "100",
                          __Updated: "20240801T080000Z",
                          __Created: "20240601T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      Business: {
                        _id: "{0DA0000A-DAAA-DAAA-DAAA-DAAA0000000A}",
                        _template: "Lookup Item",
                        _templateFullName: "Common/Lookup Item",
                        _version: 1,
                        _fields: {
                          Title: "Business",
                          Value: "business",
                          SortOrder: "200",
                          __Updated: "20240801T080000Z",
                          __Created: "20240601T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      "media library": {
        _id: "{F1000000-0000-0000-0000-000000000001}",
        _template: "Node",
        _templateFullName: "System/Node",
        _version: 1,
        _fields: {},
        _children: {
          Images: {
            _id: "{F1A00000-0000-0000-0000-000000000001}",
            _template: "Media Folder",
            _templateFullName: "System/Media/Media Folder",
            _version: 1,
            _fields: {
              __Updated: "20250301T080000Z",
              __Created: "20240601T080000Z",
              "__Updated by": "sitecore\\admin",
            },
            _children: {
              Logo: {
                _id: "{F1A00001-0001-0001-0001-000000000001}",
                _template: "Image",
                _templateFullName: "System/Media/Image",
                _version: 1,
                _fields: {
                  Title: "Company Logo",
                  Alt: "Company Logo",
                  Extension: "png",
                  Size: "24580",
                  Width: "400",
                  Height: "120",
                  MimeType: "image/png",
                  __Updated: "20250301T080000Z",
                  __Created: "20240601T080000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {},
              },
              "Hero Banner": {
                _id: "{F1A00002-0002-0002-0002-000000000002}",
                _template: "Image",
                _templateFullName: "System/Media/Image",
                _version: 1,
                _fields: {
                  Title: "Hero Banner",
                  Alt: "Homepage Hero Banner",
                  Extension: "jpg",
                  Size: "185420",
                  Width: "1920",
                  Height: "600",
                  MimeType: "image/jpeg",
                  __Updated: "20250215T090000Z",
                  __Created: "20240701T080000Z",
                  "__Updated by": "sitecore\\author1",
                },
                _children: {},
              },
              "Contributors Photo": {
                _id: "{F1A00003-0003-0003-0003-000000000003}",
                _template: "Image",
                _templateFullName: "System/Media/Image",
                _version: 1,
                _fields: {
                  Title: "Contributors Photo",
                  Alt: "Our Contributors",
                  Extension: "jpg",
                  Size: "204800",
                  Width: "1600",
                  Height: "900",
                  MimeType: "image/jpeg",
                  __Updated: "20250110T110000Z",
                  __Created: "20240815T100000Z",
                  "__Updated by": "sitecore\\author1",
                },
                _children: {},
              },
              "Product Screenshot": {
                _id: "{F1A00004-0004-0004-0004-000000000004}",
                _template: "Image",
                _templateFullName: "System/Media/Image",
                _version: 1,
                _fields: {
                  Title: "Product Screenshot",
                  Alt: "",
                  Extension: "png",
                  Size: "312000",
                  Width: "1440",
                  Height: "900",
                  MimeType: "image/png",
                  __Updated: "20250305T140000Z",
                  __Created: "20250101T080000Z",
                  "__Updated by": "sitecore\\author2",
                },
                _children: {},
              },
            },
          },
          Documents: {
            _id: "{F1B00000-0000-0000-0000-000000000001}",
            _template: "Media Folder",
            _templateFullName: "System/Media/Media Folder",
            _version: 1,
            _fields: {
              __Updated: "20250201T080000Z",
              __Created: "20240601T080000Z",
              "__Updated by": "sitecore\\admin",
            },
            _children: {
              "Annual Report": {
                _id: "{F1B00001-0001-0001-0001-000000000001}",
                _template: "PDF",
                _templateFullName: "System/Media/PDF",
                _version: 1,
                _fields: {
                  Title: "2024 Annual Report",
                  Extension: "pdf",
                  Size: "2458000",
                  MimeType: "application/pdf",
                  __Updated: "20250201T080000Z",
                  __Created: "20250115T090000Z",
                  "__Updated by": "sitecore\\author1",
                },
                _children: {},
              },
              "Product Brochure": {
                _id: "{F1B00002-0002-0002-0002-000000000002}",
                _template: "PDF",
                _templateFullName: "System/Media/PDF",
                _version: 1,
                _fields: {
                  Title: "Product Brochure 2025",
                  Extension: "pdf",
                  Size: "1842000",
                  MimeType: "application/pdf",
                  __Updated: "20250220T100000Z",
                  __Created: "20250115T100000Z",
                  "__Updated by": "sitecore\\author2",
                },
                _children: {},
              },
              "Style Guide": {
                _id: "{F1B00003-0003-0003-0003-000000000003}",
                _template: "PDF",
                _templateFullName: "System/Media/PDF",
                _version: 1,
                _fields: {
                  Title: "Brand Style Guide",
                  Extension: "pdf",
                  Size: "956000",
                  MimeType: "application/pdf",
                  __Updated: "20250105T090000Z",
                  __Created: "20240801T080000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {},
              },
            },
          },
        },
      },
    },
  },
};

/** Snapshot of initial tree state for reset */
const TREE_DATA_SNAPSHOT = JSON.parse(JSON.stringify(TREE_DATA));

/** Returns a deep clone of the virtual tree so mutable operations get fresh state */
export function createVirtualTree(): { sitecore: SitecoreNode } {
  return JSON.parse(JSON.stringify(TREE_DATA_SNAPSHOT));
}

/** Shared mutable tree instance for the app */
export const VIRTUAL_TREE = TREE_DATA;

/** Reset the shared tree to its original state (for testing/validation) */
export function resetVirtualTree(): void {
  const fresh = JSON.parse(JSON.stringify(TREE_DATA_SNAPSHOT));
  // Deep replace: clear existing children and copy fresh ones
  VIRTUAL_TREE.sitecore._children = fresh.sitecore._children;
  VIRTUAL_TREE.sitecore._fields = fresh.sitecore._fields;
}
