import type { SitecoreNode } from "../types";

// ============================================================================
// VIRTUAL SITECORE CONTENT TREE
// ============================================================================

const TREE_DATA: { sitecore: SitecoreNode } = {
  sitecore: {
    _id: "{11111111-1111-1111-1111-111111111111}",
    _template: "Root",
    _templateFullName: "System/Root",
    _version: 1,
    _fields: {},
    _children: {
      content: {
        _id: "{0DE95AE4-41AB-4D01-9EB0-67441B7C2450}",
        _template: "Node",
        _templateFullName: "System/Node",
        _version: 1,
        _fields: {},
        _children: {
          Home: {
            _id: "{110D559F-DEA5-42EA-9C1C-8A5DF7E70EF9}",
            _template: "Sample Item",
            _templateFullName: "Sample/Sample Item",
            _version: 2,
            _fields: {
              Title: "Welcome to Sitecore",
              Text: "<p>This is the home page content.</p>",
              NavigationTitle: "Home",
              MetaDescription: "Welcome to our Sitecore-powered website.",
              MetaKeywords: "sitecore, cms, content management",
              __Updated: "20250315T103000Z",
              __Created: "20240601T080000Z",
              "__Updated by": "sitecore\\admin",
            },
            _children: {
              About: {
                _id: "{A2B3C4D5-E6F7-8901-2345-678901234567}",
                _template: "Sample Item",
                _templateFullName: "Sample/Sample Item",
                _version: 1,
                _fields: {
                  Title: "About Us",
                  Text: "<p>Learn more about our company.</p>",
                  NavigationTitle: "About",
                  ShowInNavigation: "1",
                  __Updated: "20250220T140000Z",
                  __Created: "20240710T090000Z",
                  "__Updated by": "sitecore\\author1",
                },
                _children: {
                  Team: {
                    _id: "{B1111111-1111-1111-1111-111111111111}",
                    _template: "Sample Item",
                    _templateFullName: "Sample/Sample Item",
                    _version: 1,
                    _fields: {
                      Title: "Our Team",
                      Text: "<p>Meet the team behind the product.</p>",
                      __Updated: "20250110T110000Z",
                      __Created: "20240815T100000Z",
                      "__Updated by": "sitecore\\author1",
                    },
                    _children: {
                      "Jane Smith": {
                        _id: "{B1A00001-0001-0001-0001-000000000001}",
                        _template: "Employee",
                        _templateFullName: "Project/Employee",
                        _version: 1,
                        _fields: {
                          Title: "Jane Smith",
                          JobTitle: "Chief Executive Officer",
                          Department: "Executive",
                          Email: "jane.smith@example.com",
                          Bio: "<p>Jane has led the company since 2018.</p>",
                          IsActive: "1",
                          SortOrder: "100",
                          __Updated: "20250301T090000Z",
                          __Created: "20240901T080000Z",
                          "__Updated by": "sitecore\\author1",
                        },
                        _children: {},
                      },
                      "Marcus Johnson": {
                        _id: "{B1A00002-0002-0002-0002-000000000002}",
                        _template: "Employee",
                        _templateFullName: "Project/Employee",
                        _version: 1,
                        _fields: {
                          Title: "Marcus Johnson",
                          JobTitle: "Chief Technology Officer",
                          Department: "Engineering",
                          Email: "marcus.johnson@example.com",
                          Bio: "<p>Marcus oversees all technical architecture.</p>",
                          IsActive: "1",
                          SortOrder: "200",
                          __Updated: "20250218T150000Z",
                          __Created: "20240901T083000Z",
                          "__Updated by": "sitecore\\author1",
                        },
                        _children: {},
                      },
                      "Priya Patel": {
                        _id: "{B1A00003-0003-0003-0003-000000000003}",
                        _template: "Employee",
                        _templateFullName: "Project/Employee",
                        _version: 1,
                        _fields: {
                          Title: "Priya Patel",
                          JobTitle: "VP of Design",
                          Department: "Design",
                          Email: "priya.patel@example.com",
                          Bio: "<p>Priya leads our user experience initiatives.</p>",
                          IsActive: "1",
                          SortOrder: "300",
                          __Updated: "20250205T110000Z",
                          __Created: "20240915T090000Z",
                          "__Updated by": "sitecore\\author2",
                        },
                        _children: {},
                      },
                      "David Chen": {
                        _id: "{B1A00004-0004-0004-0004-000000000004}",
                        _template: "Employee",
                        _templateFullName: "Project/Employee",
                        _version: 1,
                        _fields: {
                          Title: "David Chen",
                          JobTitle: "Senior Developer",
                          Department: "Engineering",
                          Email: "david.chen@example.com",
                          Bio: "<p>David is a full-stack developer specializing in Sitecore.</p>",
                          IsActive: "0",
                          SortOrder: "400",
                          __Updated: "20250115T100000Z",
                          __Created: "20241010T080000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                    },
                  },
                  History: {
                    _id: "{B2222222-2222-2222-2222-222222222222}",
                    _template: "Sample Item",
                    _templateFullName: "Sample/Sample Item",
                    _version: 1,
                    _fields: {
                      Title: "Our History",
                      Text: "<p>Founded in 2003.</p>",
                      __Updated: "20250105T090000Z",
                      __Created: "20240815T103000Z",
                      "__Updated by": "sitecore\\admin",
                    },
                    _children: {},
                  },
                  Careers: {
                    _id: "{A2C00001-0001-0001-0001-000000000001}",
                    _template: "Landing Page",
                    _templateFullName: "Project/Landing Page",
                    _version: 1,
                    _fields: {
                      Title: "Join Our Team",
                      Text: "<p>We are always looking for talented individuals.</p>",
                      HeroBanner: "{F1A00001-0001-0001-0001-000000000001}",
                      CallToAction: "View Open Positions",
                      ShowInNavigation: "1",
                      __Updated: "20250308T140000Z",
                      __Created: "20250101T090000Z",
                      "__Updated by": "sitecore\\author1",
                    },
                    _children: {},
                  },
                },
              },
              Products: {
                _id: "{C3D4E5F6-7890-1234-5678-901234567890}",
                _template: "Folder",
                _templateFullName: "Common/Folder",
                _version: 1,
                _fields: {
                  __Updated: "20250301T080000Z",
                  __Created: "20240615T120000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {
                  "Product A": {
                    _id: "{D1111111-1111-1111-1111-111111111111}",
                    _template: "Product",
                    _templateFullName: "Project/Product",
                    _version: 1,
                    _fields: {
                      Title: "Product A",
                      Text: "<p>Our flagship product.</p>",
                      Price: "499.99",
                      SKU: "PROD-A-001",
                      Category: "Enterprise",
                      IsActive: "1",
                      ReleaseDate: "20240901",
                      __Updated: "20250310T160000Z",
                      __Created: "20240901T080000Z",
                      "__Updated by": "sitecore\\author2",
                    },
                    _children: {
                      Features: {
                        _id: "{D1F00001-0001-0001-0001-000000000001}",
                        _template: "Folder",
                        _templateFullName: "Common/Folder",
                        _version: 1,
                        _fields: {
                          __Updated: "20250310T160000Z",
                          __Created: "20240901T090000Z",
                          "__Updated by": "sitecore\\author2",
                        },
                        _children: {
                          "Cloud Integration": {
                            _id: "{D1F00002-0002-0002-0002-000000000002}",
                            _template: "Feature",
                            _templateFullName: "Project/Feature",
                            _version: 1,
                            _fields: {
                              Title: "Cloud Integration",
                              Text: "<p>Seamless cloud deployment and scaling.</p>",
                              Priority: "High",
                              __Updated: "20250310T160000Z",
                              __Created: "20240905T100000Z",
                              "__Updated by": "sitecore\\author2",
                            },
                            _children: {},
                          },
                          "API Access": {
                            _id: "{D1F00003-0003-0003-0003-000000000003}",
                            _template: "Feature",
                            _templateFullName: "Project/Feature",
                            _version: 1,
                            _fields: {
                              Title: "API Access",
                              Text: "<p>RESTful API for all operations.</p>",
                              Priority: "Medium",
                              __Updated: "20250228T120000Z",
                              __Created: "20240905T103000Z",
                              "__Updated by": "sitecore\\author2",
                            },
                            _children: {},
                          },
                        },
                      },
                    },
                  },
                  "Product B": {
                    _id: "{D2222222-2222-2222-2222-222222222222}",
                    _template: "Product",
                    _templateFullName: "Project/Product",
                    _version: 1,
                    _fields: {
                      Title: "Product B",
                      Text: "<p>Enterprise solution.</p>",
                      Price: "1299.00",
                      SKU: "PROD-B-001",
                      Category: "Enterprise",
                      IsActive: "1",
                      ReleaseDate: "20240915",
                      __Updated: "20250228T120000Z",
                      __Created: "20240915T100000Z",
                      "__Updated by": "sitecore\\author2",
                    },
                    _children: {},
                  },
                  "Product C": {
                    _id: "{D3333333-3333-3333-3333-333333333333}",
                    _template: "Product",
                    _templateFullName: "Project/Product",
                    _version: 1,
                    _fields: {
                      Title: "Product C",
                      Text: "<p>Developer toolkit.</p>",
                      Price: "199.00",
                      SKU: "PROD-C-001",
                      Category: "Developer",
                      IsActive: "1",
                      ReleaseDate: "20241001",
                      __Updated: "20250120T143000Z",
                      __Created: "20241001T090000Z",
                      "__Updated by": "sitecore\\admin",
                    },
                    _children: {},
                  },
                  "Product D": {
                    _id: "{D4444444-4444-4444-4444-444444444444}",
                    _template: "Product",
                    _templateFullName: "Project/Product",
                    _version: 1,
                    _fields: {
                      Title: "Product D",
                      Text: "<p>Analytics dashboard.</p>",
                      Price: "799.00",
                      SKU: "PROD-D-001",
                      Category: "Analytics",
                      IsActive: "0",
                      ReleaseDate: "20250301",
                      __Updated: "20250305T090000Z",
                      __Created: "20250201T080000Z",
                      "__Updated by": "sitecore\\author2",
                    },
                    _children: {},
                  },
                },
              },
              News: {
                _id: "{E4F5A6B7-C8D9-0123-4567-890123456789}",
                _template: "Folder",
                _templateFullName: "Common/Folder",
                _version: 1,
                _fields: {
                  __Updated: "20250312T090000Z",
                  __Created: "20240701T080000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {
                  "2025 Roadmap": {
                    _id: "{E1111111-1111-1111-1111-111111111111}",
                    _template: "Article",
                    _templateFullName: "Project/Article",
                    _version: 1,
                    _fields: {
                      Title: "2025 Product Roadmap",
                      Text: "<p>Exciting things ahead.</p>",
                      Summary: "A look at what we are building this year.",
                      Author: "Jane Smith",
                      PublishDate: "20250105",
                      Category: "Announcements",
                      Tags: "roadmap, strategy, 2025",
                      __Updated: "20250312T090000Z",
                      __Created: "20250105T080000Z",
                      "__Updated by": "sitecore\\author1",
                    },
                    _children: {},
                  },
                  "Sitecore Launch": {
                    _id: "{E2222222-2222-2222-2222-222222222222}",
                    _template: "Article",
                    _templateFullName: "Project/Article",
                    _version: 1,
                    _fields: {
                      Title: "New Sitecore Features",
                      Text: "<p>Latest platform updates.</p>",
                      Summary: "Exploring the newest features in the Sitecore platform.",
                      Author: "Marcus Johnson",
                      PublishDate: "20241120",
                      Category: "Technology",
                      Tags: "sitecore, platform, update",
                      __Updated: "20250215T110000Z",
                      __Created: "20241120T100000Z",
                      "__Updated by": "sitecore\\author2",
                    },
                    _children: {},
                  },
                  "Company Update": {
                    _id: "{E3333333-3333-3333-3333-333333333333}",
                    _template: "Article",
                    _templateFullName: "Project/Article",
                    _version: 1,
                    _fields: {
                      Title: "Q1 Company Update",
                      Text: "<p>A summary of our progress in the first quarter.</p>",
                      Summary: "Key highlights from Q1 including new hires and product milestones.",
                      Author: "Jane Smith",
                      PublishDate: "20250401",
                      Category: "Company",
                      Tags: "quarterly, update, growth",
                      __Updated: "20250401T090000Z",
                      __Created: "20250325T100000Z",
                      "__Updated by": "sitecore\\author1",
                    },
                    _children: {},
                  },
                  "Security Best Practices": {
                    _id: "{E4444444-4444-4444-4444-444444444444}",
                    _template: "Article",
                    _templateFullName: "Project/Article",
                    _version: 1,
                    _fields: {
                      Title: "Security Best Practices for Sitecore",
                      Text: "<p>How to keep your Sitecore instance secure.</p>",
                      Summary: "",
                      Author: "David Chen",
                      PublishDate: "20250210",
                      Category: "Technology",
                      Tags: "security, best practices",
                      __Updated: "20250210T140000Z",
                      __Created: "20250205T100000Z",
                      "__Updated by": "sitecore\\admin",
                    },
                    _children: {},
                  },
                },
              },
            },
          },
          Data: {
            _id: "{0DA00001-DA1A-DA1A-DA1A-DA1A00000001}",
            _template: "Folder",
            _templateFullName: "Common/Folder",
            _version: 1,
            _fields: {
              __Updated: "20250101T080000Z",
              __Created: "20240601T080000Z",
              "__Updated by": "sitecore\\admin",
            },
            _children: {
              Settings: {
                _id: "{0DA00002-DA2A-DA2A-DA2A-DA2A00000002}",
                _template: "Configuration",
                _templateFullName: "Project/Configuration",
                _version: 1,
                _fields: {
                  Title: "Global Settings",
                  SiteName: "Corporate Website",
                  DefaultLanguage: "en",
                  MaxPageSize: "50",
                  EnableSearch: "1",
                  AnalyticsEnabled: "1",
                  CacheTimeout: "3600",
                  __Updated: "20250310T100000Z",
                  __Created: "20240601T080000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {},
              },
              Lookups: {
                _id: "{0DA00003-DA3A-DA3A-DA3A-DA3A00000003}",
                _template: "Folder",
                _templateFullName: "Common/Folder",
                _version: 1,
                _fields: {
                  __Updated: "20250101T080000Z",
                  __Created: "20240601T090000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {
                  Countries: {
                    _id: "{0DA00004-DA4A-DA4A-DA4A-DA4A00000004}",
                    _template: "Folder",
                    _templateFullName: "Common/Folder",
                    _version: 1,
                    _fields: {
                      __Updated: "20240801T080000Z",
                      __Created: "20240601T090000Z",
                      "__Updated by": "sitecore\\admin",
                    },
                    _children: {
                      "United States": {
                        _id: "{0DA00005-DA5A-DA5A-DA5A-DA5A00000005}",
                        _template: "Lookup Item",
                        _templateFullName: "Common/Lookup Item",
                        _version: 1,
                        _fields: {
                          Title: "United States",
                          Value: "US",
                          SortOrder: "100",
                          __Updated: "20240801T080000Z",
                          __Created: "20240601T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      Canada: {
                        _id: "{0DA00006-DA6A-DA6A-DA6A-DA6A00000006}",
                        _template: "Lookup Item",
                        _templateFullName: "Common/Lookup Item",
                        _version: 1,
                        _fields: {
                          Title: "Canada",
                          Value: "CA",
                          SortOrder: "200",
                          __Updated: "20240801T080000Z",
                          __Created: "20240601T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      "United Kingdom": {
                        _id: "{0DA00007-DA7A-DA7A-DA7A-DA7A00000007}",
                        _template: "Lookup Item",
                        _templateFullName: "Common/Lookup Item",
                        _version: 1,
                        _fields: {
                          Title: "United Kingdom",
                          Value: "UK",
                          SortOrder: "300",
                          __Updated: "20240801T080000Z",
                          __Created: "20240601T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                    },
                  },
                  Categories: {
                    _id: "{0DA00008-DA8A-DA8A-DA8A-DA8A00000008}",
                    _template: "Folder",
                    _templateFullName: "Common/Folder",
                    _version: 1,
                    _fields: {
                      __Updated: "20240801T080000Z",
                      __Created: "20240601T090000Z",
                      "__Updated by": "sitecore\\admin",
                    },
                    _children: {
                      Technology: {
                        _id: "{0DA00009-DA9A-DA9A-DA9A-DA9A00000009}",
                        _template: "Lookup Item",
                        _templateFullName: "Common/Lookup Item",
                        _version: 1,
                        _fields: {
                          Title: "Technology",
                          Value: "technology",
                          SortOrder: "100",
                          __Updated: "20240801T080000Z",
                          __Created: "20240601T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                      Business: {
                        _id: "{0DA0000A-DAAA-DAAA-DAAA-DAAA0000000A}",
                        _template: "Lookup Item",
                        _templateFullName: "Common/Lookup Item",
                        _version: 1,
                        _fields: {
                          Title: "Business",
                          Value: "business",
                          SortOrder: "200",
                          __Updated: "20240801T080000Z",
                          __Created: "20240601T090000Z",
                          "__Updated by": "sitecore\\admin",
                        },
                        _children: {},
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      "media library": {
        _id: "{F1000000-0000-0000-0000-000000000001}",
        _template: "Node",
        _templateFullName: "System/Node",
        _version: 1,
        _fields: {},
        _children: {
          Images: {
            _id: "{F1A00000-0000-0000-0000-000000000001}",
            _template: "Media Folder",
            _templateFullName: "System/Media/Media Folder",
            _version: 1,
            _fields: {
              __Updated: "20250301T080000Z",
              __Created: "20240601T080000Z",
              "__Updated by": "sitecore\\admin",
            },
            _children: {
              "Logo": {
                _id: "{F1A00001-0001-0001-0001-000000000001}",
                _template: "Image",
                _templateFullName: "System/Media/Image",
                _version: 1,
                _fields: {
                  Title: "Company Logo",
                  Alt: "Company Logo",
                  Extension: "png",
                  Size: "24580",
                  Width: "400",
                  Height: "120",
                  MimeType: "image/png",
                  __Updated: "20250301T080000Z",
                  __Created: "20240601T080000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {},
              },
              "Hero Banner": {
                _id: "{F1A00002-0002-0002-0002-000000000002}",
                _template: "Image",
                _templateFullName: "System/Media/Image",
                _version: 1,
                _fields: {
                  Title: "Hero Banner",
                  Alt: "Homepage Hero Banner",
                  Extension: "jpg",
                  Size: "185420",
                  Width: "1920",
                  Height: "600",
                  MimeType: "image/jpeg",
                  __Updated: "20250215T090000Z",
                  __Created: "20240701T080000Z",
                  "__Updated by": "sitecore\\author1",
                },
                _children: {},
              },
              "Team Photo": {
                _id: "{F1A00003-0003-0003-0003-000000000003}",
                _template: "Image",
                _templateFullName: "System/Media/Image",
                _version: 1,
                _fields: {
                  Title: "Team Photo",
                  Alt: "Our Team",
                  Extension: "jpg",
                  Size: "204800",
                  Width: "1600",
                  Height: "900",
                  MimeType: "image/jpeg",
                  __Updated: "20250110T110000Z",
                  __Created: "20240815T100000Z",
                  "__Updated by": "sitecore\\author1",
                },
                _children: {},
              },
              "Product Screenshot": {
                _id: "{F1A00004-0004-0004-0004-000000000004}",
                _template: "Image",
                _templateFullName: "System/Media/Image",
                _version: 1,
                _fields: {
                  Title: "Product Screenshot",
                  Alt: "",
                  Extension: "png",
                  Size: "312000",
                  Width: "1440",
                  Height: "900",
                  MimeType: "image/png",
                  __Updated: "20250305T140000Z",
                  __Created: "20250101T080000Z",
                  "__Updated by": "sitecore\\author2",
                },
                _children: {},
              },
            },
          },
          Documents: {
            _id: "{F1B00000-0000-0000-0000-000000000001}",
            _template: "Media Folder",
            _templateFullName: "System/Media/Media Folder",
            _version: 1,
            _fields: {
              __Updated: "20250201T080000Z",
              __Created: "20240601T080000Z",
              "__Updated by": "sitecore\\admin",
            },
            _children: {
              "Annual Report": {
                _id: "{F1B00001-0001-0001-0001-000000000001}",
                _template: "PDF",
                _templateFullName: "System/Media/PDF",
                _version: 1,
                _fields: {
                  Title: "2024 Annual Report",
                  Extension: "pdf",
                  Size: "2458000",
                  MimeType: "application/pdf",
                  __Updated: "20250201T080000Z",
                  __Created: "20250115T090000Z",
                  "__Updated by": "sitecore\\author1",
                },
                _children: {},
              },
              "Product Brochure": {
                _id: "{F1B00002-0002-0002-0002-000000000002}",
                _template: "PDF",
                _templateFullName: "System/Media/PDF",
                _version: 1,
                _fields: {
                  Title: "Product Brochure 2025",
                  Extension: "pdf",
                  Size: "1842000",
                  MimeType: "application/pdf",
                  __Updated: "20250220T100000Z",
                  __Created: "20250115T100000Z",
                  "__Updated by": "sitecore\\author2",
                },
                _children: {},
              },
              "Style Guide": {
                _id: "{F1B00003-0003-0003-0003-000000000003}",
                _template: "PDF",
                _templateFullName: "System/Media/PDF",
                _version: 1,
                _fields: {
                  Title: "Brand Style Guide",
                  Extension: "pdf",
                  Size: "956000",
                  MimeType: "application/pdf",
                  __Updated: "20250105T090000Z",
                  __Created: "20240801T080000Z",
                  "__Updated by": "sitecore\\admin",
                },
                _children: {},
              },
            },
          },
        },
      },
    },
  },
};

/** Returns a deep clone of the virtual tree so mutable operations get fresh state */
export function createVirtualTree(): { sitecore: SitecoreNode } {
  return JSON.parse(JSON.stringify(TREE_DATA));
}

/** Shared mutable tree instance for the app */
export const VIRTUAL_TREE = TREE_DATA;
